### ISSUE TITLE
Lack of Indicated Die

### ISSUE THREAD

**Issue by JaceR** [ricegf/elven-fire#35]
On page 44 of the Manual, in 3.6 Treasures, under Artifacts/"3. Rings, Gems, Scrolls," it reads "If the rolled ability has counter-abilities, identified in brackets and preceded by a '+', roll the indicated die and if a 1..." However, there is no die indicated on the treasure sheet, nor does this specify where to find the 'indicated die.' However, I think that with all counter-abilities, the intended die roll here is a d4, yes? We should adjust that reference to merely rolling a d4.

**Comment by sarinilla** [comment]
Above the abilities section, it reads "Add Counter Ability on d4=1"

**Comment by ricegf** [comment]
I think I used "indicated die", because the game also supports a d6-only experience. In that case, it's a 1 out of 6 chance (since you can't roll a 1 1/2!).
